spring:
  cloud:
    gateway:
      routes:
        - id: ai-scanner
          uri: lb://ai-scanner
          predicates:
            - Path=/api/v1/ai-scanner/**
            - Method=GET, POST, DELETE
          filters:
            - StripPrefix=3
            - name: CircuitBreaker
              args:
                name: ai-scanner
                statusCodes: 500, 404, 502, 503, 504
                fallbackUri: forward:
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-duration-threshold: 7s
        slow-call-rate-threshold: 50

    instances:
      ai-scanner:
        base-config: default


  timelimiter:
    configs:
      default:
        timeout-duration: 5s
    instances:
      ai-scanner:
        base-config: default